services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aiKnowLedge-qdrant
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"
    ports:
      - "8502:6333"

  mongo:
    image: mongo:latest
    container_name: aiKnowLedge-mongo
    volumes:
      - "./mongo_storage:/data/db:z"
    ports:
      - "8503:27017"
