services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aiknowledge-qdrant
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"
    ports:
      - "8502:6333"
    networks:
      - aiknowledge

  mongo:
    image: mongo:latest
    container_name: aiknowledge-mongo
    volumes:
      - "./mongo_storage:/data/db:z"
    ports:
      - "8503:27017"
    networks:
      - aiknowledge

  aiknowledge:
    image: aiknowledge:latest
    container_name: aiknowledge-streamlit
    depends_on:
      - qdrant
      - mongo
    volumes:
      - "./uploaded_file:/aiknowledge/uploaded_file:z"
    ports:
      - "8501:8501"
    networks:
      - aiknowledge

volumes:
  qdrant_storage:
  mongo_storage:
  uploaded_file:

networks:
  aiknowledge:
    driver: bridge