services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: intflex_audit_qdrant
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"
    ports:
      - "8502:6333"
    networks:
      - intflex_audit

  mongo:
    image: mongo:latest
    container_name: intflex_audit_mongo
    volumes:
      - "./mongo_storage:/data/db:z"
    ports:
      - "8503:27017"
    networks:
      - intflex_audit

  intflex_audit:
    image: intflex_audit:latest
    container_name: intflex_audit_streamlit
    depends_on:
      - qdrant
      - mongo
    volumes:
      - "./uploaded_file:/intflex_audit/uploaded_file:z"
    ports:
      - "8501:8501"
    networks:
      - intflex_audit

volumes:
  qdrant_storage:
  mongo_storage:
  uploaded_file:

networks:
  intflex_audit:
    driver: bridge