services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aiknowledge-qdrant
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"
    ports:
      - "8502:6333"

  mongo:
    image: mongo:latest
    container_name: aiknowledge-mongo
    volumes:
      - "./mongo_storage:/data/db:z"
    ports:
      - "8503:27017"

  aiknowledge:
    image: aiknowledge:latest
    container_name: aiknowledge-streamlit
    ports:
      - "8501:8501"
    privileged: true
