[server]
# Enables support for Cross-Origin Resource Sharing (CORS) protection, for
# added security.
# Due to conflicts between CORS and XSRF, if `backend.enableXsrfProtection` is
# on and `backend.enableCORS` is off at the same time, we will prioritize
# `backend.enableXsrfProtection`.
# Default: true
enableCORS = true

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added
# security.
# Due to conflicts between CORS and XSRF, if `backend.enableXsrfProtection` is
# on and `backend.enableCORS` is off at the same time, we will prioritize
# `backend.enableXsrfProtection`.
# Default: true
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 200


[theme]
base = "light"
primaryColor="#9554d6"
backgroundColor="#2E0854"
secondaryBackgroundColor="#740cac"
textColor="#FFFFFF"
font="sans serif"
